# migrate-blog-seo.ps1
# Mass-migrates all blog files from manual Helmet to BlogSEO component
$ErrorActionPreference = "Stop"

Set-Location "c:\Users\lenovo\careercompas"
$blogsDir = "src\blogs"

# [filename, slug, title, description, date, keywords]
$blogData = @(
    @("AICareerPath2026.tsx","ai-career-path-2026","AI Career Path India 2026: Complete Guide","Explore AI career paths in India 2026. Machine learning, NLP, computer vision roles. Salaries, skills, roadmap, and top companies hiring AI professionals.","2026-02-15","AI career India, machine learning career, artificial intelligence jobs India, AI engineer salary, AI career 2026, CareerCompass"),
    @("AIRevolution.tsx","ai-career-guidance","How AI is Revolutionizing Career Guidance","Discover how AI-powered career guidance is transforming how students find their ideal careers. Explore CareerCompass AI assessment technology.","2025-07-15","AI career guidance, artificial intelligence career counseling, AI career assessment, CareerCompass AI"),
    @("AgricultureAgritechCareer2026.tsx","agriculture-agritech-career-2026","Agriculture and AgriTech Career India 2026","Complete guide to Agriculture and AgriTech careers in India 2026. Explore farming technology, agribusiness, research, and government agriculture roles.","2026-02-18","agriculture career India, agritech career, farming technology jobs, agribusiness career, ICAR careers, CareerCompass"),
    @("AnimationVFXCareer2026.tsx","animation-vfx-career-2026","Animation and VFX Career India 2026: Complete Guide","Complete guide to Animation and VFX careers in India. Salaries, skills, top studios, courses, and how to become an animator or VFX artist.","2026-02-15","animation career India, VFX career, 3D animation jobs, visual effects career, animation salary India, CareerCompass"),
    @("ArchitectureInteriorDesignCareer2026.tsx","architecture-interior-design-career-2026","Architecture and Interior Design Career India 2026","Complete guide to Architecture and Interior Design careers in India. Learn about NATA, B.Arch, salaries, top colleges, and emerging design opportunities.","2026-02-20","architecture career India, interior design career, B.Arch course, NATA exam, architect salary India, CareerCompass"),
    @("ArtsCareerPaths.tsx","arts-career-paths","Arts Career Paths: High-Paying Humanities Jobs India","Discover high-paying career paths in Arts and Humanities. From law to journalism, UX design to civil services - Arts opens more doors than you think.","2026-01-12","arts career paths, humanities career, arts jobs India, career after arts stream, law journalism career India, CareerCompass"),
    @("AviationAerospaceCareer2026.tsx","aviation-aerospace-career-2026","Aviation and Aerospace Career India 2026: Complete Guide","Guide to Aviation and Aerospace careers in India 2026. Pilot training, aerospace engineering, air traffic control, cabin crew, and aviation management.","2026-02-18","aviation career India, pilot career India, aerospace engineering, air traffic control, cabin crew career, CareerCompass"),
    @("BeginnerAIProjects.tsx","beginner-ai-projects","Zero Cost AI Portfolio: 3 Beginner Projects to Start Your AI Career","Build real AI projects without spending money. Learn Python, ML, and data science through hands-on beginner AI projects that impress recruiters.","2025-12-15","beginner AI projects, AI portfolio, free AI projects, machine learning beginner, Python AI projects, CareerCompass"),
    @("BiotechCareer2026.tsx","biotech-career-2026","Biotechnology Career India 2026: Salaries, Skills and Opportunities","Complete guide to Biotechnology careers in India. Research, pharma, bioinformatics, genomics - explore biotech salary ranges and top companies hiring.","2026-02-15","biotechnology career India, biotech jobs, bioinformatics career, pharma research, biotech salary India 2026, CareerCompass"),
    @("BlockchainCareer2026.tsx","blockchain-web3-career-2026","Blockchain and Web3 Career India 2026: Salary, Skills and Roadmap","Complete guide to Blockchain and Web3 careers in India 2026. Solidity developer, crypto analyst, DeFi engineer - skills, salaries, and top companies.","2026-02-15","blockchain career India, Web3 career, crypto developer jobs, Solidity developer salary, DeFi career, CareerCompass"),
    @("CACareerIndia2026.tsx","ca-career-india-2026","Chartered Accountant CA Career India 2026: Complete Guide","Complete guide to CA career in India. CA exam pattern, salary after CA Rs8-50 LPA, articleship, Big 4 firms, and career growth as a Chartered Accountant.","2026-03-15","CA career India, chartered accountant salary, ICAI exam, CA articleship, Big 4 India career, CareerCompass"),
    @("CareerAdviceBlog.tsx","never-take-career-advice-from-parents","Why You Should Never Take Career Advice from Your Parents","Honest advice on why traditional parental career guidance may be outdated. Learn how to make career decisions based on modern market realities.","2025-10-15","career advice parents, career guidance India, wrong career advice, career decisions, modern career guidance, CareerCompass"),
    @("CareerAfterBTech.tsx","career-after-btech","Career Options After BTech: Jobs, GATE, MBA, MS and More","Complete guide to career options after BTech. Explore campus placements, GATE exam, MBA, MS abroad, startups, and government jobs for BTech graduates.","2026-01-20","career after btech, jobs after btech, GATE exam, MBA after engineering, MS abroad after btech, CareerCompass"),
    @("CareerMirage.tsx","career-mirage","The Career Mirage: Why Your Dream Job May Disappoint You","The truth about dream jobs vs. real career satisfaction. Learn how to avoid the career mirage and find work that genuinely fulfills you.","2025-08-18","career mirage, dream job reality, career satisfaction, job disappointment, career guidance, CareerCompass"),
    @("CivilEngineeringCareer2026.tsx","civil-engineering-career-2026","Civil Engineering Career India 2026: Salary, Scope and Roadmap","Complete guide to Civil Engineering careers in India 2026. Structural, environmental, transportation engineering - salaries, government jobs, and growth.","2026-03-15","civil engineering career India, civil engineer salary, structural engineering, UPSC IES exam, PSU civil jobs, CareerCompass"),
    @("CloudComputingCareer2026.tsx","cloud-computing-career-2026","Cloud Computing Career India 2026: AWS, Azure and GCP Guide","Complete guide to Cloud Computing careers in India. AWS, Azure, GCP certifications, DevOps roles, salaries Rs8-50 LPA, and career roadmap.","2026-02-15","cloud computing career India, AWS career, Azure certification, GCP jobs India, DevOps salary 2026, CareerCompass"),
    @("CollegeVsPassion.tsx","college-vs-passion","Prestigious College vs Your Passion: What Matters More in India?","Should you choose the most prestigious college or follow your passion? Data-driven breakdown of what actually matters for career success in India.","2025-09-10","college vs passion, IIT vs passion, prestigious college career, career choice India, which college to choose, CareerCompass"),
    @("CommerceCareerPaths.tsx","commerce-career-paths-after-12th","25 Commerce Career Paths After 12th: Beyond CA and MBA","Discover 25+ career options after Commerce stream. Finance, banking, digital marketing, entrepreneurship - high-paying careers beyond CA and MBA.","2025-09-10","commerce career paths, career after commerce, jobs after 12th commerce, CA alternatives, CFP career India, CareerCompass"),
    @("ContentCreatorCareer2026.tsx","content-creator-career","Content Creator Career India 2026: From Hobby to Full-Time Income","Complete guide to building a content creator career in India. YouTube, Instagram, blogging - monetization strategies, earnings, and brand deals.","2026-01-10","content creator career, YouTube career India, influencer income, blogging career, social media income India, CareerCompass"),
    @("CybersecurityCareer2026.tsx","cybersecurity-career-2026","Cybersecurity Career India 2026: Salary, Certifications and Roadmap","Complete guide to Cybersecurity careers in India. Ethical hacking, CISSP, CEH, bug bounty - salaries Rs8-40 LPA and how to enter the field.","2026-01-10","cybersecurity career India, ethical hacking career, CISSP certification, CEH exam, cyber security salary India, CareerCompass"),
    @("DefenceCareerIndia2026.tsx","defence-career-india-2026","Defence Career India 2026: Army, Navy, Air Force and UPSC CDS","Complete guide to Defence careers in India. Indian Army, Navy, Air Force officer roles - NDA, UPSC CDS, AFCAT exams, salary, and life in uniform.","2026-03-15","defence career India, Indian Army officer, NDA exam, UPSC CDS, Air Force career India, CareerCompass"),
    @("DigitalMarketingCareer.tsx","digital-marketing-career","Digital Marketing Career India 2026: Salary, Skills and Roadmap","Complete guide to Digital Marketing careers in India. SEO, PPC, social media, content marketing - salaries and how to get hired in 2026.","2026-01-12","digital marketing career India, SEO career, PPC jobs, social media marketing career, digital marketing salary, CareerCompass"),
    @("EmergingCareers.tsx","top-careers-india","10 Emerging Careers Shaping the Future of Work in India","Discover 10 emerging, high-growth career paths in India. From AI to green energy - future-proof careers with high salaries and demand.","2025-06-15","emerging careers India, future careers, high growth jobs India, new careers 2026, future jobs India, CareerCompass"),
    @("EnvironmentalScienceCareer2026.tsx","environmental-science-career-2026","Environmental Science Career India 2026: Green Careers Guide","Complete guide to Environmental Science careers in India. Climate tech, environmental consulting, UPSC IFS, green energy - salaries and opportunities.","2026-03-15","environmental science career, green career India, climate tech jobs, environmental consultant, UPSC IFS, CareerCompass"),
    @("EventManagementCareer2026.tsx","event-management-career-2026","Event Management Career India 2026: Salary, Courses and Growth","Complete guide to Event Management careers in India. Wedding planner, corporate events, sports management - salaries, courses, and top companies.","2026-02-15","event management career India, event planner salary, wedding planner career, corporate event management, CareerCompass"),
    @("FashionDesignCareer2026.tsx","fashion-design-career-2026","Fashion Design Career India 2026: NIFT, Salary and Opportunities","Complete guide to Fashion Design careers in India. NIFT admission, fashion designer salary Rs4-25 LPA, textile design, and styling careers.","2026-02-15","fashion design career India, NIFT admission, fashion designer salary, textile design career, styling career, CareerCompass"),
    @("FinanceCareerPaths2026.tsx","finance-career-paths-2026","Finance Career Paths India 2026: Investment Banking, CFA and More","Complete guide to Finance careers in India. Investment banking, CFA, financial analysis, wealth management - salaries and career pathways.","2026-02-15","finance career India, investment banking career, CFA certification, financial analyst salary, wealth management career, CareerCompass"),
    @("FreelanceCareer2026.tsx","freelance-career-guide","Freelance Career Guide India 2026: How to Earn Rs1-10L Per Month","Complete guide to building a successful freelance career in India. Top platforms, skills in demand, pricing strategy, and how to get your first client.","2026-01-10","freelance career India, freelancing guide, upwork India, fiverr India, freelance income, remote work India, CareerCompass"),
    @("FutureOfWork2035.tsx","future-of-work-2035","The Future of Work in 2035: Skills and Careers That Will Thrive","What will the job market look like in 2035? Skills in demand, careers that will survive automation, and how to future-proof your career.","2025-09-15","future of work 2035, future careers, automation jobs, skills 2035, career future India, CareerCompass"),
    @("GamingEsportsCareer2026.tsx","gaming-esports-career-2026","Gaming and Esports Career India 2026: Pro Player, Game Dev and More","Complete guide to Gaming and Esports careers in India. Professional gamer, game developer, esports commentator - salaries and how to enter the industry.","2026-03-15","gaming career India, esports career, game developer salary, pro gamer India, esports industry India, CareerCompass"),
    @("GapYearGuide2026.tsx","gap-year-guide-india-2026","Gap Year Guide India 2026: How to Make the Most of Your Time Off","Complete guide to taking a gap year in India. Study abroad preparation, skill-building, internships, travel, and UPSC preparation.","2026-03-15","gap year India, gap year after 12th, gap year after graduation, productive gap year, study abroad gap year, CareerCompass"),
    @("GovernmentJobsGuide.tsx","government-jobs-guide","Government Jobs India 2026: Complete Guide to UPSC, SSC, Banking","Complete guide to government jobs in India. UPSC, SSC, banking exams, railways, defence - salary, preparation strategy, and best government jobs.","2026-01-15","government jobs India, UPSC exam, SSC exam, banking exam India, sarkari naukri, best government jobs India, CareerCompass"),
    @("GraphicDesignCareer2026.tsx","graphic-design-career-2026","Graphic Design Career India 2026: Salary, Skills and Portfolio Guide","Complete guide to Graphic Design careers in India. UI/UX influence, branding, motion design - salary Rs4-25 LPA, Adobe tools, and freelance opportunities.","2026-03-15","graphic design career India, graphic designer salary, Adobe career, branding career, motion design career India, CareerCompass"),
    @("GreenEnergyCareers2026.tsx","green-energy-careers-2026","Green Energy Career India 2026: Solar, Wind and Clean Tech Jobs","Complete guide to Green Energy and Clean Tech careers in India. Solar engineer, wind energy, climate tech - government incentives and salary prospects.","2026-02-15","green energy career India, solar energy jobs, wind energy career, clean tech India, renewable energy salary, CareerCompass"),
    @("HRManagementCareer2026.tsx","hr-management-career-2026","HR Management Career India 2026: Salary, Skills and Growth Path","Complete guide to HR Management careers in India. Human resources, talent acquisition, L and D, HRBP roles - salaries Rs5-25 LPA and career growth.","2026-03-15","HR career India, human resources career, talent acquisition career, HR manager salary India, SHRM certification, CareerCompass"),
    @("HealthcareCareers2025.tsx","healthcare-careers-2025","Healthcare Careers India 2025: Beyond MBBS - Allied Health and More","Explore diverse healthcare career options in India beyond MBBS. Nursing, physiotherapy, medical lab tech, healthcare management - salaries and scope.","2025-08-15","healthcare careers India, allied health careers, medical career beyond MBBS, nursing career, physiotherapy career, CareerCompass"),
    @("HospitalityTourismCareer2026.tsx","hospitality-tourism-career-2026","Hospitality and Tourism Career India 2026: Hotels, Travel and More","Complete guide to Hospitality and Tourism careers in India. Hotel management, travel industry, airline hospitality - IHM admission, salaries, and growth.","2026-02-15","hospitality career India, hotel management career, tourism career, IHM admission, travel industry jobs India, CareerCompass"),
    @("InterviewTips2026.tsx","interview-tips-freshers-2026","Job Interview Tips for Freshers 2026: Complete Preparation Guide","Complete interview preparation guide for freshers. Common interview questions, how to answer them, body language tips, salary negotiation, and follow-up emails.","2026-02-15","interview tips freshers, job interview preparation, common interview questions, salary negotiation, fresher interview India, CareerCompass"),
    @("LawCareerIndia2026.tsx","law-career-india-2026","Law Career India 2026: CLAT, LLB, Salary and Career Paths","Complete guide to Law careers in India. CLAT exam, LLB, corporate law, criminal law - lawyer salary Rs8-50 LPA and top law colleges in India.","2026-02-15","law career India, CLAT exam, LLB course, lawyer salary India, corporate lawyer, criminal law career, CareerCompass"),
    @("MBAvsMS.tsx","mba-vs-ms","MBA vs MS: Which One Should You Choose After Engineering?","Complete comparison of MBA vs MS after engineering. ROI, career opportunities, costs, top colleges - which is right for you in 2026?","2026-01-12","MBA vs MS, MBA after engineering, MS abroad, which is better MBA or MS, MBA salary vs MS salary, CareerCompass"),
    @("MediaJournalism2026.tsx","media-journalism-career-2026","Media and Journalism Career India 2026: Salary, Scope and Opportunities","Complete guide to Media and Journalism careers in India. News anchor, digital journalist, PR, content strategy - salary and top media companies hiring.","2026-02-15","media career India, journalism career, news anchor India, digital journalism, PR career India, CareerCompass"),
    @("MerchantNavyCareer2026.tsx","merchant-navy-career-2026","Merchant Navy Career India 2026: Salary, Courses and Life at Sea","Complete guide to Merchant Navy careers in India. Captain, marine engineer, deck officer - salary Rs8-25 LPA, DNS/GME courses, and admission process.","2026-02-15","merchant navy career India, marine engineer salary, DNS course, GME course, merchant navy salary India, CareerCompass"),
    @("NEETCounseling2026.tsx","neet-counseling-2026","NEET Counseling 2026: Complete Guide to MBBS and BDS Admission","Complete guide to NEET 2026 counseling for MBBS, BDS, AYUSH admissions. Learn about MCC counseling, state counseling, AIQ quota, choice filling, and seat allotment.","2026-01-15","NEET counseling 2026, NEET counseling process, MCC counseling, MBBS admission 2026, BDS admission, NEET seat allotment, NEET choice filling, CareerCompass"),
    @("NursingCareer2026.tsx","nursing-career-india-2026","Nursing Career India 2026: Salary, Abroad Opportunities and Growth","Complete guide to Nursing careers in India and abroad. BSc Nursing, GNM, NCLEX for USA/UK/Canada - salary Rs3-50 LPA, scope, and career growth.","2026-03-15","nursing career India, BSc nursing, NCLEX exam, nursing salary India, nursing abroad, nurse career growth, CareerCompass"),
    @("NutritionDietitianCareer2026.tsx","nutrition-dietitian-career-2026","Nutrition and Dietitian Career India 2026: Salary, Courses and Scope","Complete guide to Nutrition and Dietitian careers in India. Clinical nutritionist, sports dietitian, wellness consultant - salaries and top institutes.","2026-03-15","nutrition career India, dietitian career, nutritionist salary India, clinical nutrition, sports nutritionist, CareerCompass"),
    @("PassionIsntEnough.tsx","passion-isnt-enough","Passion Isnt Enough: What a Successful Career Really Requires","Why following your passion alone is not a career strategy. Discover what skills, market demand, and planning are required for real career success.","2025-07-18","passion career advice, career planning India, career success tips, career guidance, follow your passion myth, CareerCompass"),
    @("PerfectCareerMyth.tsx","perfect-career-myth","The Perfect Career Myth: Why There Is No Such Thing as the Dream Job","Why the perfect career is a myth and how chasing it can hurt you. Learn a realistic approach to career satisfaction and meaningful work.","2025-08-20","perfect career myth, dream job myth, career satisfaction, realistic career advice, career planning India, CareerCompass"),
    @("PersonalBranding2026.tsx","personal-branding-career-success-2026","Personal Branding for Career Success India 2026: Complete Guide","How to build a personal brand that accelerates your career. LinkedIn optimization, portfolio building, thought leadership for Indian professionals in 2026.","2026-01-08","personal branding career, LinkedIn personal brand, personal brand India, career brand building, thought leadership India, CareerCompass"),
    @("PharmacyCareer2026.tsx","pharmacy-career-2026","Pharmacy Career India 2026: B.Pharm, D.Pharm, Salary and Scope","Complete guide to Pharmacy careers in India. B.Pharm, D.Pharm, clinical pharmacist, pharmaceutical research - salary Rs4-20 LPA and top pharma companies.","2026-02-15","pharmacy career India, B.Pharm course, pharmacist salary India, pharmaceutical career, drug regulatory affairs, CareerCompass"),
    @("ProductManagementCareer2026.tsx","product-management-career","Product Management Career India 2026: PM Roadmap and Salary Guide","Complete guide to Product Management careers in India. How to become a PM, essential skills, salary Rs15-60 LPA, and top companies hiring PMs.","2026-02-15","product management career India, product manager salary, how to become PM, PM roadmap, product manager skills, CareerCompass"),
    @("PsychologyCareer2026.tsx","psychology-career-paths","Psychology Career Paths India 2026: Clinical, Industrial and More","Complete guide to Psychology careers in India. Clinical psychologist, counselor, industrial psychologist - salary, courses, and mental health career opportunities.","2026-01-10","psychology career India, clinical psychologist career, counselor career, industrial psychology, psychologist salary India, CareerCompass"),
    @("RealEstateCareer2026.tsx","real-estate-career-2026","Real Estate Career India 2026: Agent, Developer and PropTech Jobs","Complete guide to Real Estate careers in India. Real estate agent, property developer, RERA, PropTech startups - commissions, salary, and growth opportunities.","2026-02-15","real estate career India, property dealer career, RERA agent, real estate developer, PropTech career, CareerCompass"),
    @("RemoteWorkGuide2026.tsx","remote-work-guide-2026","Remote Work India 2026: How to Find and Land Remote Jobs","Complete guide to finding and thriving in remote work in India. Top remote job platforms, skills in demand, home office setup, and productivity tips.","2026-01-10","remote work India, remote jobs India, work from home career, remote job platforms India, digital nomad India, CareerCompass"),
    @("ResumeTips.tsx","resume-tips","Resume Writing Tips India 2026: ATS-Optimized Resume Guide","Complete resume writing guide for Indian job seekers. ATS optimization, format, keywords, skills section - how to write a resume that gets interviews.","2025-05-15","resume tips India, how to write resume, ATS resume, resume format India, job resume guide, CareerCompass"),
    @("RightCareerPath.tsx","right-career-path-after-12th","Choosing the Right Career Path After 12th: A Complete Guide","How to choose the right career after 12th grade in India. Science, Commerce, Arts stream - assessment-based career selection guide for students.","2025-08-15","career after 12th, right career after 12th, stream selection after 12th, career guidance after 12th India, CareerCompass"),
    @("RoboticsIoTCareer2026.tsx","robotics-iot-career-2026","Robotics and IoT Career India 2026: Salary, Skills and Opportunities","Complete guide to Robotics and IoT careers in India. Automation engineer, robotics developer, IoT specialist - salary Rs8-35 LPA and top companies.","2026-03-15","robotics career India, IoT career, automation engineer salary, robotics engineer India, internet of things career, CareerCompass"),
    @("SocialWorkCareer2026.tsx","social-work-career-india-2026","Social Work Career India 2026: NGO, UPSC and International Roles","Complete guide to Social Work careers in India. MSW, NGO work, UPSC social services, international development - salary and impact-driven career paths.","2026-03-15","social work career India, NGO career, MSW course, social worker salary India, UPSC social services, CareerCompass"),
    @("SportsManagementCareer2026.tsx","sports-management-career-2026","Sports Management Career India 2026: IPL, Olympic and Global Roles","Complete guide to Sports Management careers in India. Sports agent, team manager, sports marketing, IPL jobs - salary and how to enter the sports industry.","2026-02-15","sports management career India, sports agent career, IPL jobs, sports marketing India, sports management course, CareerCompass"),
    @("StudyAbroadGuide2026.tsx","study-abroad-guide-2026","Study Abroad Guide India 2026: USA, UK, Canada, Australia, Germany","Complete guide to studying abroad from India in 2026. GRE, IELTS, TOEFL, scholarships, visa process, top universities, and ROI of studying abroad.","2026-01-15","study abroad India, study USA from India, study UK from India, GRE preparation, IELTS exam, study abroad scholarships, CareerCompass"),
    @("SupplyChainCareer2026.tsx","supply-chain-career-2026","Supply Chain and Logistics Career India 2026: Salary and Roadmap","Complete guide to Supply Chain and Logistics careers in India. Operations manager, supply chain analyst, warehousing - salaries and top companies.","2026-02-15","supply chain career India, logistics career, operations manager salary, warehouse management, SCM career India, CareerCompass"),
    @("TeachingCareer2026.tsx","teaching-edtech-career-2026","Teaching and EdTech Career India 2026: Salary, Scope and Opportunities","Complete guide to Teaching and EdTech careers in India. School teacher, online tutor, EdTech startups - salary Rs3-30 LPA and CTET/TET preparation.","2026-02-15","teaching career India, EdTech career, CTET exam, teacher salary India, online tutor career, EdTech jobs, CareerCompass"),
    @("TopSkills2026.tsx","top-skills-2026","Top Skills in Demand 2026: What Employers Are Hiring For Now","The most in-demand skills for 2026. Technical skills, soft skills, and emerging skills that will get you hired - backed by job market data.","2026-01-15","top skills 2026, skills in demand, what skills to learn, employer demanded skills, future skills 2026, CareerCompass"),
    @("UPSCCivilServicesCareer2026.tsx","upsc-civil-services-career-2026","UPSC Civil Services Career 2026: IAS, IFS, IPS Complete Guide","Complete guide to UPSC Civil Services career. IAS, IPS, IFS preparation, UPSC exam pattern, salary, posting, and life as a civil servant in India.","2026-02-15","UPSC career, IAS officer career, civil services India, UPSC preparation, IAS salary, UPSC exam pattern, CareerCompass"),
    @("UXUIDesignCareer2026.tsx","ux-ui-design-career-2026","UX UI Design Career India 2026: Salary Rs8-35 LPA, Skills and Tools","Complete guide to UX/UI Design careers in India. Figma, user research, product design - salary Rs8-35 LPA, portfolio tips, and top companies hiring.","2026-02-15","UX design career India, UI designer salary, Figma career, product design India, UX researcher salary, CareerCompass"),
    @("WrongCareerPath.tsx","wrong-career-path","Are You on the Wrong Career Path? 7 Signs You Should Pivot","7 clear signs you are in the wrong career and how to pivot without starting from scratch. Stories, data, and a practical framework for career change.","2025-07-20","wrong career path, career change India, career pivot, switch career, unhappy at work India, CareerCompass")
)

$migrated = 0
$skipped = 0
$errors = 0

foreach ($row in $blogData) {
    $filename  = $row[0]
    $slug      = $row[1]
    $title     = $row[2]
    $descr     = $row[3]
    $date      = $row[4]
    $keywords  = $row[5]
    
    $fullPath = Join-Path $blogsDir $filename
    
    if (-not (Test-Path $fullPath)) {
        Write-Host "  [MISSING] $filename" -ForegroundColor Magenta
        $errors++
        continue
    }
    
    $content = Get-Content $fullPath -Raw -Encoding UTF8
    
    # Skip already migrated files
    if ($content -match 'import BlogSEO') {
        Write-Host "  [SKIP] $filename (already migrated)" -ForegroundColor Yellow
        $skipped++
        continue
    }
    
    # Replace import
    $newContent = $content -replace "import \{ Helmet \} from 'react-helmet-async';", "import BlogSEO from '../components/BlogSEO';"
    
    # Check if a Helmet block actually exists
    if ($newContent -match '(?s)<Helmet>.*?</Helmet>') {
        # Build BlogSEO JSX replacement
        $replacement = "            <BlogSEO`r`n                title=`"$title`"`r`n                description=`"$descr`"`r`n                slug=`"$slug`"`r`n                date=`"$date`"`r`n                keywords=`"$keywords`"`r`n            />"
        
        # Replace <Helmet>...</Helmet> block (multi-line)
        $newContent = [regex]::Replace($newContent, '(?s)<Helmet>.*?</Helmet>', $replacement)
        
        [System.IO.File]::WriteAllText((Get-Location).Path + "\" + $fullPath, $newContent, [System.Text.Encoding]::UTF8)
        Write-Host "  [OK]  $filename -> /blog/$slug" -ForegroundColor Green
        $migrated++
    } else {
        Write-Host "  [ERR] $filename - Helmet block not found" -ForegroundColor Red
        $errors++
    }
}

Write-Host ""
Write-Host "=== Migration Complete ===" -ForegroundColor Cyan
Write-Host "  Migrated : $migrated" -ForegroundColor Green
Write-Host "  Skipped  : $skipped" -ForegroundColor Yellow
Write-Host "  Errors   : $errors" -ForegroundColor Red
